services:
  full-babylon:
    build: .
    env_file:
      - .env.full.babylon
    command: npm run dev:compare
    restart: unless-stopped
    ports:
      - "5100:5100" # web-host
      - "5101:5101" # 3d-widget
      - "5102:5102" # combined-app

  webhost-only-babylon:
    build: .
    env_file:
      - .env.webhost.babylon
    command: npm run dev:host
    restart: unless-stopped
    ports:
      - "5103:5103"
    depends_on:
      - full-babylon

  full-three:
    build: .
    env_file:
      - .env.full.three
    command: npm run dev:three:compare
    restart: unless-stopped
    ports:
      - "5200:5200" # web-host
      - "5201:5201" # 3d-widget
      - "5202:5202" # combined-app

  webhost-only-three:
    build: .
    env_file:
      - .env.webhost.three
    command: npm run dev:three:host
    restart: unless-stopped
    ports:
      - "5203:5203"
    depends_on:
      - full-three
